import {esc,productName,contents,footer} from '/files/narrative.js';
import {renderInterior} from '/files/pages.js';
import {soilPlate,macro} from '/files/photo-story.js';
const image=(file,alt,extra='')=>`<img src="/files/${file}" alt="${esc(alt)}" ${extra}>`;
// Canonical source SVGs are copied unchanged; the mask preserves their proportions.
const skuBrand={monstera:['monstera-moss','#4A7C59'],ficus:['ficus-cosmos','#BE3A6B'],anthurium:['anturium-poppy','#C03A30'],aglaonema:['aglaonema-zagogulya','#7E6AAF'],spathiphyllum:['spatifillum-kaplya','#2878AE'],zamioculcas:['zamiokulkas-buttercup','#C47A10'],epipremnum:['epipremnum-moss','#4A7C59']};
const doodle=(name,slot,sku=false)=>`<span class="atelier-brand-doodle atelier-doodle-${slot} ${sku?'atelier-sku-doodle':''}" aria-hidden="true" style="--doodle:url('/files/brand-doodle-${name}.svg')"></span>`;
const isBox=s=>['anthurium','epipremnum'].includes(s.slug);
const cover=s=>isBox(s)?`box-${s.slug}.png`:`soil-${s.slug}-cutout.webp`;
function checkout(d,state,compact=false){
 const s=d.skus[state.plant],v=s.sizes[state.size],ready=state.shopPlantChosen&&state.shopSizeChosen;
 return `<div class="atelier-checkout ${compact?'compact':''}"><div><strong>${esc(ready?v.price:s.priceFrom)}</strong><span>${ready?esc(v.volume)+' · ':''}за весь бокс</span></div><button class="atelier-buy" ${ready?'data-marketplace':'data-shop-next'}>${ready?'Купить бокс':state.shopPlantChosen?'Выбрать размер':'Выбрать бокс'} <span aria-hidden="true">↗</span></button></div>`;
}
function order(d,state){const s=d.skus[state.plant];return `<section class="atelier-order" id="atelier-order" aria-label="Выбрать и купить бокс"><label for="atelier-plant">Твоё растение</label><select id="atelier-plant" data-hybrid-plant><option value="" disabled ${state.shopPlantChosen?'':'selected'}>Выбери свой «Заземли»</option>${d.skus.map((s,i)=>`<option value="${i}" ${state.shopPlantChosen&&state.plant===i?'selected':''}>${esc(productName(s))}</option>`).join('')}</select><div class="atelier-size-label">Диаметр нового горшка <details><summary aria-label="Как выбрать размер">?</summary><p>Измерь новый горшок по верхнему краю. Если размер между указанными — <a href="mailto:team@zazemli.com">поможем с объёмом</a>.</p></details></div><div class="atelier-sizes" role="group" aria-label="Диаметр нового горшка">${s.sizes.map((v,i)=>`<button data-shop-size="${i}" aria-pressed="${state.shopSizeChosen&&state.size===i}"><b>${esc(d.volumeTiers.find(t=>t.volume===v.volume)?.pot||v.volume)}</b><span>${esc(v.volume)} грунта</span></button>`).join('')}</div>${checkout(d,state)}<p class="atelier-market-note">Покупка на маркетплейсе</p></section>`}
function gallery(s,state,product){const n=state.slide||0,files=[cover(s),`soil-${s.slug}-photo.webp`,`diary-${s.slug}.webp`,'diary-spread.webp'],labels=[isBox(s)?'Бокс и комплектация':'Грунт из бокса','Рецептурная земля','Дневник на год','Разворот дневника'];return `<figure class="atelier-object">${doodle(product?skuBrand[s.slug][0]:'leaf','hero',product)}<div class="atelier-photo"><button data-enlarge="${files[n]}" aria-label="Рассмотреть ${esc(productName(s))}">${image(files[n],productName(s)+' · '+labels[n],'fetchpriority="high" decoding="async"')}</button><span class="atelier-photo-label">${esc(s.number)} / ${labels[n]}</span></div><figcaption><span>${esc(productName(s))}</span><div class="atelier-photo-controls"><button data-shop-slide="${(n+3)%4}" aria-label="Предыдущая фотография">←</button><span>0${n+1} <i>/ 04</i></span><button data-shop-slide="${(n+1)%4}" aria-label="Следующая фотография">→</button></div></figcaption></figure>`}
function collection(d){return `<section class="atelier-collection" id="atelier-collection"><header class="atelier-heading"><span class="atelier-eyebrow">03 / Коллекция</span><div><h2>Для каждого растения —<br><em>своя земля</em></h2><p>Найди свой «Заземли». Дальше останется выбрать размер.</p></div><div class="atelier-rail-controls"><button data-atelier-scroll="-1" aria-label="Предыдущие боксы">←</button><button data-atelier-scroll="1" aria-label="Следующие боксы">→</button></div></header><div class="atelier-rail">${d.skus.map((s,i)=>`<button class="atelier-card" data-shop-plant="${i}" data-shop-result><div class="atelier-card-image">${image(cover(s),productName(s),'loading="lazy" decoding="async"')}<span aria-hidden="true">↗</span></div><span class="atelier-eyebrow">${esc(s.number)} / Бокс на одну пересадку</span><h3>${esc(productName(s))}</h3><span class="atelier-card-price">${esc(s.priceFrom)}</span></button>`).join('')}</div></section>`}
function soil(d,s){return `<section class="atelier-soil"><header class="atelier-heading"><span class="atelier-eyebrow">04 / Рецептура${doodle('star','soil')}</span><div><h2>Земля имеет<br><em>значение</em></h2><p>Разным корням нужны разные условия.</p></div></header><div class="atelier-soil-layout"><div class="atelier-soil-text"><span class="atelier-big-number">${s.components}<small>компонентов</small></span><h3>В грунте для «${esc(productName(s))}»</h3><p>${esc(s.whyProse)}</p><p>Компоненты уже отмерены и смешаны. Тебе не нужно покупать их по отдельности.</p><button class="atelier-link" data-route="lab" data-recipe-link>Рассмотреть рецептуру <span>↗</span></button><div class="atelier-macro-pair">${macro('kora','Кора')}${macro('zeo','Цеолит')}</div></div>${soilPlate(s,d)}</div></section>`}
function diary(s){return `<section class="atelier-diary"><div class="atelier-diary-visual">${image('diary-spread.webp','Разворот дневника растения на год','loading="lazy"')}<figure>${image(`diary-${s.slug}.webp`,productName(s)+' · дневник','loading="lazy"')}</figure></div><div class="atelier-diary-copy"><span class="atelier-eyebrow">06 / Дневник в комплекте</span><h2>Пересадка — сегодня.<br><em>Забота — весь год</em></h2><p>Открывай нужный сезон: когда поливать, подкармливать и на что смотреть. Записывай, как растёт твоё растение. Бумажный дневник на год уже в боксе.</p><button class="atelier-link" data-enlarge="diary-spread.webp">Рассмотреть дневник <span>↗</span>${image('diary-spread.webp','Разворот дневника','hidden')}</button></div></section>`}
const navigation=()=>`<nav class="atelier-nav" aria-label="Навигация сайта"><button class="atelier-brand" data-route="home">ЗАЗЕМЛИ<span>Боксы для пересадки растений</span></button><div><button data-route="collection">Коллекция</button><button data-route="lab">Лаборатория</button><button class="atelier-nav-buy" data-shop-next>Выбрать бокс <span>↗</span></button></div></nav>`;
export function renderAtelier(page,d,state,helpers){
 if(!['home','product','collection'].includes(page))return renderInterior(1,page,d,state,{...helpers,nav:navigation});
 const s=d.skus[state.plant],product=page==='product',brand=skuBrand[s.slug],accent=product?brand[1]:'#4A7C59';
 const hero=`<section class="atelier-hero"><div class="atelier-intro"><span class="atelier-eyebrow">Земля и забота — всё, что нужно</span><h1 data-reveal>${product?`Заземли<br><em>${esc(s.accusative)}</em>`:'Заземли растение.<br><em>Заземли себя</em>'}</h1><p>Бокс на одну пересадку.<br>Грунт под твоё растение и всё, что понадобится.</p></div>${gallery(s,state,product)}${order(d,state)}</section>`;
 const inventory=`<div class="atelier-inventory-strip"><span><i>01</i> Принадлежности</span><span><i>02</i> Дренаж</span><span><i>03</i> Рецептурный грунт</span><span><i>04</i> Дневник на год</span><button data-jump="inside">Всё внутри ↓</button></div>`;
 return navigation()+`<div class="atelier-shell ${product?'atelier-product':''}" style="--atelier-accent:${accent};--atelier-display:${product&&s.slug==='zamioculcas'?'#1C1C1C':accent};--atelier-button-ink:${product&&s.slug==='zamioculcas'?'#1C1C1C':'#FFFFFF'}">${page==='collection'?collection(d):''}${hero}${inventory}${contents(d,s)}${page==='collection'?'':collection(d)}${soil(d,s)}<section class="atelier-ritual">${doodle('heart','ritual')}${helpers.art('hands')}<div><span class="atelier-eyebrow">05 / Маленький ритуал</span><h2>Чуть ближе<br><em>к живому</em></h2><p>Освободи место на столе.<br>Разложи всё из бокса.<br>Побудь с растением.</p><blockquote>«Чем больше цифры — тем важнее земля.»<cite>Настя, основательница ЗАЗЕМЛИ</cite></blockquote><button class="atelier-link" data-route="guide">Гайд по пересадке <span>↗</span></button></div></section>${diary(s)}<section class="atelier-finale">${doodle('wave','finale')}<span class="atelier-eyebrow">Один бокс — одна пересадка</span><h2>Земля и забота.<br><em>Всё, что нужно</em></h2><button class="atelier-buy" data-shop-next>Найти свой «Заземли» <span>↗</span></button><p>Твои растение и горшок — с тебя.</p></section></div>${footer(d,page)}<aside class="atelier-dock ${product?'atelier-product':''}" style="--atelier-accent:${accent};--atelier-button-ink:${product&&s.slug==='zamioculcas'?'#1C1C1C':'#FFFFFF'}" aria-label="Покупка выбранного бокса"><span>${esc(productName(s))}</span>${checkout(d,state,true)}</aside>`;
}
export const atelierNotes=`<b>Ателье пересадки / концепт + быстрая покупка.</b> Один цельный вариант: крупный предметный кадр, костяной фон, фирменный moss, Mulish + Commissioner, оригинальные дудлы и точная типографика и выбор бокса на первом экране. Фотография, растение, размер и цена связаны; детали комплекта открыты ниже. <p>Фирменная система сверена с БЗ Насти (GitHub, b2f141c): Bone #F6F4F0 / Charcoal #1C1C1C / Moss #4A7C59; typography v3.0, color-system, iconography, PATCH-1 и PATCH-1.1 от 30.08. На карточке — цвет и дудл выбранного растения. Тексты — черновик для просмотра Настей.</p><p>Референсы найдены в <a href="https://www.reddit.com/r/web_design/comments/1wd7yvf/best_designed_websites_you_look_at_for_inspo/" target="_blank" rel="noreferrer">обсуждении Reddit</a>: <a href="https://www.hotel-weekend.com/" target="_blank" rel="noreferrer">Hôtel Weekend</a> — атмосфера и фотография; <a href="https://worklouder.cc/" target="_blank" rel="noreferrer">Work Louder</a> — акцент на предмете. <a href="https://www.reddit.com/r/typography/comments/c27zig/" target="_blank" rel="noreferrer">Aesop упомянут в обсуждении типографики</a>. Это интерпретация приёмов, а не копия сайтов и не доказательство роста продаж.</p><p>Фото собранных боксов пока есть для антуриума и эпипремнума; остальные представлены собственной землёй. Площадка покупки ещё не выбрана.</p>`;
