import {esc,productName,footer,contents,diaryValue} from '/files/narrative.js';
import {renderInterior} from '/files/pages.js';
export const shopDirections=[
 {name:'Фото → покупка',entry:'Знаю своё растение',flow:['Узнать бокс на фото','Выбрать растение','Указать горшок','Купить на маркетплейсе'],show:'Крупный товар, все растения, размеры и точная цена рядом.',defer:'Рецептура и история — ниже покупки.',risk:'Для пяти боксов нужна своя предметная съёмка.',metric:'Доля посетителей, выбравших растение и размер.',recommend:true},
 {name:'Два выбора — один бокс',entry:'Хочу понять, какой набор мне подходит',flow:['Выбрать растение','Выбрать размер','Рассмотреть результат','Купить'],show:'Два явно пронумерованных выбора над фотографией.',defer:'Подробности появляются у уже выбранного бокса.',risk:'Форма может выглядеть утилитарно; фотография сохраняет характер бренда.',metric:'Доля завершивших оба выбора.'},
 {name:'Витрина семи боксов',entry:'Хочу увидеть весь ассортимент',flow:['Просмотреть фото','Открыть свой бокс','Выбрать размер','Купить'],show:'Сетка товаров с полным названием и ценой от.',defer:'Обоснование цены — в выбранной карточке.',risk:'Не хватает пяти фото боксов; пока показываем их собственную землю.',metric:'Переходы из списка к выбору объёма.'},
 {name:'Сравнение по делу',entry:'Хочу быстро найти нужное название',flow:['Найти растение в списке','Сверить варианты','Указать размер','Купить'],show:'Семь строк: товар, доступные горшки, цена.',defer:'Подробная рецептура — по ссылке.',risk:'Менее эмоционально, чем витрина с большими фото.',metric:'Время от входа до выбора своего бокса.'},
 {name:'Каталог без переходов',entry:'Смотрю несколько боксов',flow:['Нажать на товар','Смотреть его рядом','Выбрать размер','Купить'],show:'Каталог слева, выбранный бокс с покупкой справа.',defer:'История и наука — ниже каталога.',risk:'На телефоне панель идёт после списка; нужен понятный переход к выбору.',metric:'Доля переходов к покупке без открытия отдельной страницы.',recommend:true},
 {name:'Покупка из распаковки',entry:'Хочу понять, за что плачу',flow:['Рассмотреть комплект','Нажать на предметы','Выбрать растение и размер','Купить'],show:'Настоящий открытый бокс, интерактив и видимая опись.',defer:'Научные подробности вынесены в лабораторию.',risk:'Первый экран насыщеннее; важен баланс фотографии и выбора.',metric:'Выбор размера после взаимодействия с комплектацией.'},
 {name:'Сначала горшок',entry:'Знаю размер нового горшка',flow:['Указать диаметр','Увидеть подходящие боксы','Выбрать растение','Купить'],show:'Три размера горшка и ассортимент для выбранного размера.',defer:'Литры показываются вместе с результатом, а не требуют расчёта.',risk:'Диапазоны взяты из текущей модели; для промежуточных размеров нужна помощь.',metric:'Доля пользователей, нашедших доступную комбинацию.'},
 {name:'Фото объясняют',entry:'Не хочу читать длинное описание',flow:['Перелистать фото','Увидеть землю и дневник','Выбрать вариант','Купить'],show:'Одна фотолента: продукт, раскладка, дневник, разворот.',defer:'Длинные пояснения — после галереи.',risk:'Фото должны отвечать на вопросы, иначе листание станет лишним действием.',metric:'Выбор размера после просмотра дополнительных кадров.'},
 {name:'Покупка с доказательством',entry:'Почему это дороже обычного грунта?',flow:['Увидеть бокс и цену','Проверить состав','Выбрать размер','Купить'],show:'Фото, количество компонентов и конкретное объяснение рецептуры.',defer:'Точные доли и источники доступны в лаборатории.',risk:'Плотнее по тексту; полезнее сомневающимся покупателям.',metric:'Переход к покупке после просмотра рецептуры.'},
 {name:'Мобильная карточка',entry:'Пришёл с телефона за конкретным боксом',flow:['Увидеть товар','Выбрать растение и размер','Проверить цену','Купить'],show:'Компактная карточка, миниатюры и нижняя строка покупки.',defer:'Дневник, ритуал и характеристики идут ниже.',risk:'Закреплённая покупка занимает часть экрана; оставляем только цену и действие.',metric:'Выбор варианта и переход на маркетплейс с телефона.',recommend:true}
];
const realBox=s=>['anthurium','epipremnum'].includes(s.slug);
const cover=s=>realBox(s)?`box-${s.slug}.png`:`soil-${s.slug}-cutout.webp`;
const photo=(file,alt,cls='')=>`<img class="${cls}" src="/files/${file}" alt="${esc(alt)}" loading="lazy" decoding="async">`;
const tiers=(d,s)=>s.sizes.map(v=>d.volumeTiers.find(t=>t.volume===v.volume)?.pot||v.volume).join(' · ');
function plantButtons(d,state){return `<div class="shop-plants" role="group" aria-label="Растение">${d.skus.map((s,i)=>`<button data-shop-plant="${i}" aria-pressed="${state.shopPlantChosen&&state.plant===i}">${esc(productName(s))}</button>`).join('')}</div>`}
function sizes(d,state){const s=d.skus[state.plant];return `<div class="shop-sizes" role="group" aria-label="Диаметр нового горшка">${s.sizes.map((v,i)=>`<button data-shop-size="${i}" aria-pressed="${state.shopSizeChosen&&state.size===i}"><b>${esc(d.volumeTiers.find(t=>t.volume===v.volume)?.pot||v.volume)}</b><span>${esc(v.volume)} грунта</span></button>`).join('')}</div>`}
function buy(d,state,cls=''){const s=d.skus[state.plant],v=s.sizes[state.size],ready=state.shopPlantChosen&&state.shopSizeChosen;return `<div class="shop-checkout ${cls}"><div><strong>${esc(ready?v.price:s.priceFrom)}</strong><span>${ready?esc(v.volume)+' · за весь бокс':'за весь бокс'}</span></div><button class="shop-cta" ${ready?'data-marketplace':'data-shop-next'}>${ready?'Купить на маркетплейсе ↗':!state.shopPlantChosen?'Выбрать растение':'Выбрать размер'}</button></div>`}
const kitSummary=()=>`<ul class="shop-kit-summary"><li>Грунт под растение</li><li>Дренаж</li><li>Принадлежности для пересадки</li><li>Дневник на год</li></ul>`;
function panel(d,state,{plants=true}={}){const s=d.skus[state.plant];return `<section class="shop-panel" id="shop-selection" aria-label="Выбор бокса"><span class="shop-kicker">Бокс на одну пересадку</span><h1>${esc(productName(s))}</h1>${plants?`<div class="shop-field"><h2>1. Твоё растение</h2>${plantButtons(d,state)}</div>`:''}<div class="shop-field"><h2>${plants?'2. ':''}Диаметр нового горшка</h2>${sizes(d,state)}<details class="shop-size-help"><summary>Как измерить горшок</summary><p>Измерь диаметр нового горшка по верхнему краю. Если размер между указанными — <a href="mailto:team@zazemli.com">поможем подобрать объём</a>.</p></details></div>${buy(d,state)}<p class="shop-market-note">Оплата и доставка — на маркетплейсе</p>${kitSummary()}<p class="shop-own-pot">Растение и горшок — с тебя.</p><div class="shop-detail-links"><button data-jump="inside">Вся комплектация ↓</button><button data-route="lab" data-recipe-link>Рецептура ↗</button></div></section>`}
function gallery(s,state,{film=false}={}){const slides=[cover(s),`soil-${s.slug}-photo.webp`,`diary-${s.slug}.webp`,'diary-spread.webp'];const captions=[realBox(s)?'Бокс и комплектация':'Грунт из бокса', 'Рецептурная земля', 'Дневник растения на год','Дневник: один год рядом'];const n=state.slide||0;return `<section class="shop-gallery ${film?'shop-film':''}" aria-label="Фотографии ${esc(productName(s))}"><button class="shop-main-photo" data-enlarge="${slides[n]}">${photo(slides[n],productName(s)+' · '+captions[n])}</button><div class="shop-photo-caption"><span>${captions[n]}</span><span>${n+1} / 4</span></div><div class="shop-thumbnails" role="group" aria-label="Кадры бокса">${slides.map((file,i)=>`<button data-shop-slide="${i}" aria-label="${captions[i]}" aria-pressed="${n===i}">${photo(file,captions[i])}<span>${i+1}</span></button>`).join('')}</div></section>`}
function catalog(d,state,{rows=false,filter=false}={}){const list=d.skus.map((s,i)=>({s,i})).filter(({s})=>!filter||state.shopPot==null||s.sizes.some(v=>v.volume===d.volumeTiers[state.shopPot].volume));return `<section class="shop-catalog ${rows?'shop-rows':''}" id="shop-catalog" aria-label="Семь боксов коллекции">${list.map(({s,i})=>`<button class="shop-product-card" data-shop-plant="${i}" data-shop-result aria-pressed="${state.shopPlantChosen&&state.plant===i}"><div class="shop-card-photo">${photo(cover(s),productName(s))}</div><div><span class="shop-kicker">${esc(s.number)}</span><h2>${esc(productName(s))}</h2><p>${esc(tiers(d,s))}</p><strong>${esc(s.priceFrom)}</strong><span class="shop-card-link">Выбрать бокс ↗</span></div></button>`).join('')}</section>`}
function intro(id){return `<header class="shop-intro"><span class="shop-kicker">Земля и забота — всё, что нужно</span><h1 data-reveal>${id===3||id===5?'Семь растений.<br><em>Свой бокс для каждого.</em>':id===4?'Найди свой <em>«Заземли».</em>':id===7?'Начнём <em>с горшка.</em>':'Заземли растение.<br><em>Заземли себя.</em>'}</h1><p>Грунт под твоё растение и всё для пересадки — в одной коробке.</p></header>`}
function evidence(s){return `<section class="shop-evidence"><span class="shop-kicker">${s.components} компонентов в грунте</span><h2>Почему такая земля</h2><p>${esc(s.whyProse)}</p><button data-route="lab" data-recipe-link>Состав и точные доли ↗</button></section>`}
export function renderCommerce(id,page,d,state,helpers){
 if(!['home','collection','product'].includes(page))return renderInterior(id,page,d,state,helpers);
 const s=d.skus[state.plant],p=panel(d,state),g=gallery(s,state,{film:id===8});
 let hero='';
 if(page==='product')hero=`<div class="shop-product-layout">${g}${p}${id===9?evidence(s):''}</div>`;
 else switch(id){
 case 1:hero=`<div class="shop-split">${g}${p}</div>`;break;
 case 2:hero=`${intro(id)}<div class="shop-step-banner"><span>01 / Растение</span>${plantButtons(d,state)}<span>02 / Новый горшок</span>${sizes(d,state)}</div><div class="shop-split shop-result">${g}${panel(d,state,{plants:false})}</div>`;break;
 case 3:hero=`${intro(id)}${catalog(d,state)}<div class="shop-split shop-result">${g}${p}</div>`;break;
 case 4:hero=`${intro(id)}<div class="shop-catalog-split">${catalog(d,state,{rows:true})}<div class="shop-picked">${g}${p}</div></div>`;break;
 case 5:hero=`${intro(id)}<div class="shop-catalog-split">${catalog(d,state)}<div class="shop-picked">${g}${p}</div></div>`;break;
 case 6:hero=`<div class="shop-unbox">${contents(d,s)}${p}</div>`;break;
 case 7:hero=`${intro(id)}<div class="shop-pot-picker" role="group" aria-label="Размер нового горшка">${d.volumeTiers.map((v,i)=>`<button data-shop-pot="${i}" aria-pressed="${state.shopPot===i}"><span class="shop-pot-icon" aria-hidden="true">⌑</span><b>${esc(v.pot)}</b><span>${esc(v.volume)} грунта</span></button>`).join('')}</div><p class="shop-filter-note">${state.shopPot==null?'Выбери размер, чтобы увидеть доступные боксы.':'Боксы для горшка '+esc(d.volumeTiers[state.shopPot].pot)} <button data-shop-pot="all">Показать все</button></p>${catalog(d,state,{filter:true})}<div class="shop-split shop-result">${g}${p}</div>`;break;
 case 8:hero=`<div class="shop-split shop-film-layout">${g}${p}</div>`;break;
 case 9:hero=`<div class="shop-proof-layout">${g}${p}${evidence(s)}</div>`;break;
 case 10:hero=`<div class="shop-split shop-mobile-first">${g}${p}</div>`;break;
 }
 return helpers.nav()+`<div class="shop-shell">${hero}<div class="shop-promise"><span>Один бокс — одна пересадка</span><span>Рецептура под конкретное растение</span><span>Дневник на год в комплекте</span></div>${id===6&&page!=='product'?'':contents(d,s)}${id===9?'':evidence(s)}<section class="shop-ritual"><div>${helpers.art('hands')}</div><div><span class="shop-kicker">Заземли себя</span><h2>Время для растения.<br><em>И для себя.</em></h2><p>Разложи принадлежности. Пересади растение. Начни его дневник.</p><button data-route="guide">Гайд по пересадке ↗</button></div></section>${diaryValue(s,helpers.art)}</div>${footer(d,page)}<aside class="shop-dock" aria-label="Быстрая покупка"><span>${esc(productName(s))}</span>${buy(d,state)}</aside>`;
}
export function study(){return `<section id="commerce-study" class="commerce-study"><span class="eyebrow">Третий слой исследования / 10 гипотез быстрой покупки</span><h2>Увидел → выбрал → купил.</h2><p class="study-lead">Большая фотография помогает понять товар. Растение, размер, полная комплектация и цена помогают принять решение. Научные подробности можно открыть позже. Ниже — разные пути к покупке; рост конверсии ещё предстоит проверить.</p><div class="study-three"><div><b>01 / AS IS</b><p>Снимки действующего zazemli.com. Как человек выбирает сегодня.</p></div><div><b>02 / Концепты × 10</b><p>Текущие визуальные направления с рассказом о ценности бокса.</p></div><div><b>03 / Быстрая покупка × 10</b><p>Те же направления с фотографией, выбором и ценой ближе к началу.</p></div></div><div class="study-cards">${shopDirections.map((x,i)=>`<article><span class="eyebrow">${String(i+1).padStart(2,'0')} / ${x.recommend?'Начать проверку отсюда':'Альтернативный путь'}</span><h3>${x.name}</h3><p><b>Человек:</b> «${x.entry}»</p><ol class="study-flow">${x.flow.map(t=>`<li>${t}</li>`).join('')}</ol><p><b>Сразу:</b> ${x.show}</p><p><b>Позже:</b> ${x.defer}</p><p><b>Компромисс:</b> ${x.risk}</p><p><b>Что измерить:</b> ${x.metric}</p><button data-shop-open="${i+1}">Посмотреть вариант ${String(i+1).padStart(2,'0')} ↗</button></article>`).join('')}</div><div class="study-research"><h3>Что взято из исследований</h3><ul><li>Варианты размеров видны кнопками, рядом с покупкой. <a href="https://baymard.com/blog/use-buttons-for-size-selection" target="_blank" rel="noreferrer">Baymard: выбор размера</a></li><li>Дополнительные фото доступны прямо при выборе. <a href="https://baymard.com/blog/secondary-hover-information" target="_blank" rel="noreferrer">Baymard: фотографии в каталоге</a></li><li>Основные сведения видны, дополнительные раскрываются по запросу. <a href="https://www.nngroup.com/articles/progressive-disclosure/" target="_blank" rel="noreferrer">NN/g: постепенное раскрытие</a></li><li>Быстрый просмотр полезен для оценки по фото, но не заменяет нужные характеристики. <a href="https://baymard.com/blog/mobile-desktop-quick-views" target="_blank" rel="noreferrer">Baymard: быстрый просмотр</a></li><li>Предметный каталог смежной категории — пример подачи, не доказательство конверсии. <a href="https://www.thesill.com/collections/plant-care" target="_blank" rel="noreferrer">The Sill: уход за растениями</a></li></ul><p><b>Проверка гипотез:</b> попросить человека найти бокс для своего растения и нового горшка; измерить время, ошибки выбора и переход на маркетплейс. Для вывода о покупках нужны данные площадки: сам исходящий клик покупку не доказывает.</p><p>Покупка в макете демонстрационная. Площадку, ссылки и условия доставки подключим после выбора. Рейтинги, отзывы, остатки и скидки не выдуманы. Для пяти растений пока показываем их собственную землю: фото готовых боксов ожидаются.</p></div></section>`}
